In [2]:
import pandas as pd
import numpy as np
import datetime 
from datetime import date
import nbimporter                                #library to import functions defined in other jupyter notebook but use here 
from P02RangetrialEstimation import int2date, locate_1st_day, locate_lst_day

Importing Jupyter notebook from P02RangetrialEstimation.ipynb

In [3]:
df_es_02=pd.read_csv('./Data/ES_02.csv',dtype={'date': str,'timetable': str,'max' : float ,'min' : float ,'range' : float ,'range-trail' : float,
                                              'range-avg' : float}, parse_dates=['date'])

In [4]:
df_es_02

           date    timetable      max      min  range  range-trail  range-avg
0    2009-09-28  09:00-18:30  1060.25  1037.00  23.25          0.0   0.000000
1    2009-09-29  09:00-18:30  1065.75  1053.25  12.50          0.0   0.000000
2    2009-09-30  09:00-18:30  1063.25  1041.50  21.75          0.0   0.000000
3    2009-10-01  09:00-18:30  1055.25  1031.50  23.75          0.0   0.000000
4    2009-10-02  09:00-18:30  1027.00  1012.00  15.00          0.0   0.000000
...         ...          ...      ...      ...    ...          ...        ...
2554 2019-09-02  09:00-18:30  2926.50  2889.00  37.50         14.0  19.223518
2555 2019-09-03  09:00-18:30  2914.50  2891.00  23.50         14.0  19.223518
2556 2019-09-04  09:00-18:30  2936.25  2921.50  14.75         14.0  19.223518
2557 2019-09-05  09:00-18:30  2986.50  2950.50  36.00         14.0  19.223518
2558 2019-09-06  09:00-18:30  2988.25  2972.25  16.00         14.0  19.223518

[2559 rows x 7 columns]

In [8]:
df_es_02['open', 'close-long']=np.zeros(len(df_es_02)).astype('float')

In [9]:
df_es_02

,date,timetable,max,min,range,range-trail,range-avg,open,"(open, close-long)"
0,2009-09-28,09:00-18:30,1060.25,1037.00,23.25,0.0,0.000000,0.0,0.0
1,2009-09-29,09:00-18:30,1065.75,1053.25,12.50,0.0,0.000000,0.0,0.0
2,2009-09-30,09:00-18:30,1063.25,1041.50,21.75,0.0,0.000000,0.0,0.0
3,2009-10-01,09:00-18:30,1055.25,1031.50,23.75,0.0,0.000000,0.0,0.0
4,2009-10-02,09:00-18:30,1027.00,1012.00,15.00,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...
2554,2019-09-02,09:00-18:30,2926.50,2889.00,37.50,14.0,19.223518,0.0,0.0
2555,2019-09-03,09:00-18:30,2914.50,2891.00,23.50,14.0,19.223518,0.0,0.0
2556,2019-09-04,09:00-18:30,2936.25,2921.50,14.75,14.0,19.223518,0.0,0.0
2557,2019-09-05,09:00-18:30,2986.50,2950.50,36.00,14.0,19.223518,0.0,0.0
2558,2019-09-06,09:00-18:30,2988.25,2972.25,16.00,14.0,19.223518,0.0,0.0

In [ ]:
# function to follow the daily operation and take the decision about operation long or short
def short_long_operation (year_ini, year_end, my_df):
    
    # define variables to use
    long = 'L'                                 #
    short = 'S'                                #
    operation = long                          #
    operation_ant = long                        #
    limit = 0.0                                      #
    limit_ant = 0.0                                  #
    target = 0.0                              #
    target_ant = 0.0                            #
    limit_qty_rng = 0.0                             #
    target_qty_rng = 0.0                              #
    range_trail = 0.0                                  #
    axis_size = 0.0                                   #
    tic = 0.0                                         #
    contract_qty = 0.0                                 #
    multiplier 0.0                                   #
    
    # define variable for operation
    
    long_result = 0.0                             #
    short_result = 0.0                             #
    long_accum = 0.0                             #
    short_accum = 0.0                                       #
    result_accum = 0.0                                  #
    limit_nxt = 0 - limit_qty_rng * axis_size           #
    target_nxt = 0 + target_qty_rng * axis_size          #
    operation_nxt = long                             #
    target_reached = 0                               #
    continue_no_changes = 0                            #
    
    # locate the initial and final position
    
    pt_ini = locate_1st_day('Y', year_ini, my_df, 'date')                      # locate the initial index
    pt_end = locate_lst_day('Y', year_end, my_df, 'date')                      # locate the final index
    
    # the loop
    
    for ind in  range(pt_ini, pt_end+1):
        range_trail = my_df['range-trail'][ind]
        entry = my_df['open'][ind]
        long_result = my_df['long-rst'][ind]
        short_result = my_df['short-rst'][ind]
        
        operation = operation_nxt
        limit = limit_nxt
        target = target_nxt
        
        long_accum = long_accum + long_result
        short_accum = short_accum + short_result

        continue_no_changes = 1
        
        if (operation == long):
            result_accum = result_accum + (long_result-tic) * contract_qty * multiplier
            
            if ((long_accum < limit) & (continue_no_changes == 1)):                          # overcome the limit and change to shorts
                operation_ant = long
                operation_nxt = short
                limit_ant = limit
                limit_nxt = long_accum + (limit_qty_rng * axis_size)
                target_ant = target
                target_nxt = long_accum - (target_qty_rng * axis_size)
                continue_no_changes = 0
            
            if((target_reached == 1) & (long_result <= ((0-1) * range_trail * 0.2)) & (continue_no_changes == 1)): # target reached with reverse of 20%
                operation_ant = long
                operation_nxt = short
                limit_ant = limit
                limit_nxt = long_accum + (limit_qty_rng * axis_size)
                target_ant = target
                target_nxt = long_accum - (target_qty_rng * axis_size)
                target_reached=0
                continue_no_changes=0
            
            if((long_accum > target) & (target_reached == 0) & (continue_no_changes == 1)): # target reached but waiting reverse
                target_reached=1
                operation_ant = operation
                operation_nxt = operation_ant
                limit_ant = limit
                limit_nxt = limit_ant
                target_ant = target
                target_nxt = target_ant
                continue_no_changes = 0
            
            
        if (operation == short):
            result_accum = result_accum + short_result * contract_qty * multiplier
            
            if((long_accum > limit) & (continue_no_changes == 1)):                      # overcome limit and change
                operation_ant = short
                operation_nxt = long
                limit_ant = limit
                limit_nxt = long_accum - (limit_qty_rng * axis_size)
                target_ant = target
                target_nxt = long_accum + (target_qty_rng * axis_size)
                continue_no_changes = 0
        
            if((target_reached == 1) & (long_result > (range_trail * 0.2)) & (continue_no_changes == 1)): # target reached with reverse of 20% and change
                operation_ant = short
                operation_nxt = long
                limit_ant = limit
                limit_nxt = long_accum - (limit_qty_rng * axis_size)
                target_ant = target
                target_nxt = long_accum + (target_qty_rng * axis_size)
                target_reached=0
                continue_no_changes=0
        
            if((long_accum < target) & (target_reached == 0) & (continue_no_changes == 1)):                # target reached but waiting reverse
                target_reached=1
                operation_ant = operation
                operation_nxt = operation_ant
                limit_ant = limit
                limit_nxt = limit
                target_ant = target
                target_nxt = target
                continue_no_changes = 0
                
        if (continue_no_changes == 1):         # nothing happend, no target reached, no limit overcame, continue the same
            operation_ant = operation
            operation_nxt = operation_ant
            limit_ant = limit
            limit_nxt = limit_ant
            target_ant = target
            target_nxt = target_ant

        # save the daily operation
        
        my_df['operation'][ind]=operation_ant
        my_df['target'][ind]=target_ant
        my_df['limit'][ind]=limit_ant
        my_df['contract_qty'][ind]=contract_qty
        my_df['multiplier'][ind]=multiplier
        my_df['result'][ind]= result_accum - my_df['result'][ind-1] 
        my_df['result_accum'][ind]=result_accum